# car-payment-gateway — REST Client (HomeTest.pdf)
@baseUrl = http://localhost:3003

### 0 — Health
GET {{baseUrl}}/health

### 1 — Débitos ABC1234 (IPVA 1500 venc 2024-01-10 + MULTA 300.50 venc 2024-02-15)
POST {{baseUrl}}/api/v1/debts
Content-Type: application/json

{
  "placa": "ABC1234"
}
